# Generated by Django 5.0.7 on 2024-07-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Categoria_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=100)),
                ('Cod_C', models.CharField(blank=True, max_length=20, null=True)),
                ('Costo', models.IntegerField(blank=True, null=True)),
                ('C_Costo', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('Convenio_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Convenio', models.IntegerField()),
                ('Nombre_del_convenio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('Departamento_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Departamento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LugarTrabajo',
            fields=[
                ('Id_Lugar_Trabajo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Lugar_Trabajo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('Religion_ID', models.AutoField(primary_key=True, serialize=False)),
                ('RELIGION', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('Sucursal_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Sucursal', models.CharField(max_length=50)),
                ('Nombre_oficina', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('Legajo', models.IntegerField(primary_key=True, serialize=False)),
                ('Apellido', models.CharField(max_length=100)),
                ('Nombre', models.CharField(max_length=100)),
                ('T_doc', models.CharField(blank=True, max_length=20, null=True)),
                ('Numero', models.CharField(blank=True, max_length=20, null=True)),
                ('Est_Civil', models.CharField(blank=True, max_length=20, null=True)),
                ('Edad', models.IntegerField(blank=True, null=True)),
                ('Fec_de_Nac', models.DateField(blank=True, null=True)),
                ('Nacionalidad', models.CharField(blank=True, max_length=50, null=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Normalizacion.categoria')),
                ('Convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Normalizacion.convenio')),
                ('Departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Normalizacion.departamento')),
                ('Lugar_Trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Normalizacion.lugartrabajo')),
                ('Religion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Normalizacion.religion')),
                ('Sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Normalizacion.sucursal')),
            ],
        ),
    ]
